using ArxGenBarcode.DataModels;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using ZXing;

namespace ArxGenBarcode
{
    /// <summary>
    /// Interaction logic for WindowListFormat.xaml
    /// </summary>
    public partial class WindowListFormat : Window
    {
        public WindowListFormat()
        {
            InitializeComponent();

            var allFormat = fillAll();
            var collection = allFormat;

            foreach(var format in collection)
            {
                bool allow = Current.Settings.PossibleFormats.Contains(format.BarcodeFormat);

                allFormat.First(x => x.BarcodeFormat == format.BarcodeFormat).IsAllow = allow;
            }

            listBoxAllFormats.ItemsSource = allFormat;
        }

        private void buttonOk_Click(object sender, RoutedEventArgs e)
        {
            Current.Settings.PossibleFormats = listBoxAllFormats.Items.Cast<Format>()
                                                       .Where(x => x.IsAllow)
                                                       .Select(x => x.BarcodeFormat)
                                                       .ToList();

            Close();
        }

        private List<Format> fillAll()
        {
            var allFormat = new List<Format>();

            var AZTEC = new Format(BarcodeFormat.AZTEC, "Aztec Code is a type of 2D barcode invented by Andrew Longacre, Jr. and Robert Hussey in 1995. The code was published by AIM, Inc. in 1997. Although the Aztec code was patented, that patent was officially made public domain. The aztec code is also published as ISO/IEC 24778:2008 standard. Named after the resemblance of the central finder pattern to an Aztec pyramid, Aztec code has the potential to use less space than other matrix barcodes because it does not require a surrounding blank \"quiet zone\".", "https://en.wikipedia.org/wiki/Aztec_Code", @".\Image\Aztec.png");
            var CODABAR = new Format(BarcodeFormat.CODABAR, "Codabar is a linear barcode symbology developed in 1972 by Pitney Bowes Corp. It and its variants are also known as Codeabar, Ames Code, NW-7, Monarch, Code 2 of 7, Rationalized Codabar, ANSI/AIM BC3-1995 or USD-4. Library Book Barcode Although Codabar has not been registered for US federal trademark status, its hyphenated variant Code - a - bar is a registered trademark. It was designed to be accurately read even when printed on dot - matrix printers for multi - part forms such as FedEx airbills and blood bank forms, where variants are still in use as of 2007.Although newer symbologies hold more information in a smaller space, Codabar has a large installed base in libraries.It is even possible to print Codabar codes using typewriter - like impact printers, which allows the creation of a large number of codes with consecutive numbers without having to use computer equipment. After each printed code, the printer's stamp is mechanically turned to the next number, as for example in mechanical mile counters.", "https://en.wikipedia.org/wiki/Codabar", @".\Image\Codabar.png");
            var CODE_39 = new Format(BarcodeFormat.CODE_39, "Code 39 (also known as Alpha39, Code 3 of 9, Code 3/9, Type 39, USS Code 39, or USD-3) is a variable length, discrete barcode symbology. The Code 39 specification defines 43 characters, consisting of uppercase letters(A through Z), numeric digits(0 through 9) and a number of special characters(-, ., $, /, +, %, and space).An additional character(denoted '*') is used for both start and stop delimiters.Each character is composed of nine elements: five bars and four spaces.Three of the nine elements in each character are wide(binary value 1), and six elements are narrow(binary value 0).The width ratio between narrow and wide is not critical, and may be chosen between 1:2 and 1:3. The barcode itself does not contain a check digit(in contrast to—for instance—Code 128), but it can be considered self-checking on the grounds that a single erroneously interpreted bar cannot generate another valid character. Possibly the most serious drawback of Code 39 is its low data density: It requires more space to encode data in Code 39 than, for example, in Code 128.This means that very small goods cannot be labeled with a Code 39 based barcode.However, Code 39 is still used by some postal services(although the Universal Postal Union recommends using Code 128 in all cases), and can be decoded with virtually any barcode reader.One advantage of Code 39 is that since there is no need to generate a check digit, it can easily be integrated into existing printing system by adding a barcode font to the system or printer and then printing the raw data in that font. Code 39 was developed by Dr. David Allais and Ray Stevens of Intermec in 1974.Their original design included two wide bars and one wide space in each character, resulting in 40 possible characters. Setting aside one of these characters as a start and stop pattern left 39 characters, which was the origin of the name Code 39. Four punctuation characters were later added, using no wide bars and three wide spaces, expanding the character set to 43 characters.Code 39 was later standardised as ANSI MH 10.8 M - 1983 and MIL-STD - 1189. MIL - STD - 1189 has been cancelled and replaced by ANSI / AIM BC1 / 1995, Uniform Symbology Specification — Code 39.", "https://en.wikipedia.org/wiki/Code_39", @".\Image\Code_39.png");
            var CODE_93 = new Format(BarcodeFormat.CODE_93, "Code 93 is a barcode symbology designed in 1982 by Intermec to provide a higher density and data security enhancement to Code 39. It is an alphanumeric, variable length symbology. Code 93 is used primarily by Canada Post to encode supplementary delivery information. Every symbol includes two check characters. Each Code 93 character is nine modules wide, and always has three bars and three spaces, thus the name.Each bar and space is from 1 to 4 modules wide. (For comparison, a Code 39 character consists of five bars and five spaces, three of which are wide, for a total width of 13–16 modules.) Code 93 is designed to encode the same 26 upper case letters, 10 digits and 7 special characters", "https://en.wikipedia.org/wiki/Code_93", @".\Image\CODE_93.png");
            var CODE_128 = new Format(BarcodeFormat.CODE_128, "Code 128 is a high-density linear barcode symbology defined in ISO/IEC 15417:2007. It is used for alphanumeric or numeric-only barcodes. It can encode all 128 characters of ASCII and, by use of an extension symbol (FNC4), the Latin-1 characters defined in ISO/IEC 8859-1. GS1 - 128(formerly known as UCC / EAN - 128) is a subset of Code 128 and is used extensively worldwide in shipping and packaging industries as a product identification code for the container and pallet levels in the supply chain.The symbology was formerly defined as ISO / IEC 15417:2007.", "https://en.wikipedia.org/wiki/Code_128", @".\Image\CODE_128.png");
            var DATA_MATRIX = new Format(BarcodeFormat.DATA_MATRIX, "A Data Matrix is a two-dimensional barcode consisting of black and white \"cells\" or modules arranged in either a square or rectangular pattern, also known as a matrix. The information to be encoded can be text or numeric data. Usual data size is from a few bytes up to 1556 bytes. The length of the encoded data depends on the number of cells in the matrix. Error correction codes are often used to increase reliability: even if one or more cells are damaged so it is unreadable, the message can still be read. A Data Matrix symbol can store up to 2,335 alphanumeric characters. Data Matrix symbols are rectangular, usually square in shape and composed of square \"cells\" which represent bits.Depending on the coding used, a \"light\" cell represents a 0 and a \"dark\" cell is a 1, or vice versa.Every Data Matrix is composed of two solid adjacent borders in an \"L\" shape(called the \"finder pattern\") and two other borders consisting of alternating dark and light \"cells\" or modules(called the \"timing pattern\").Within these borders are rows and columns of cells encoding information.The finder pattern is used to locate and orient the symbol while the timing pattern provides a count of the number of rows and columns in the symbol. As more data is encoded in the symbol, the number of cells(rows and columns) increases.Each code is unique.Symbol sizes vary from 10×10 to 144×144 in the new version ECC 200, and from 9×9 to 49×49 in the old version ECC 000 – 140.", "https://en.wikipedia.org/wiki/Data_Matrix", @".\Image\DATA_MATRIX.png");
            var EAN_8 = new Format(BarcodeFormat.EAN_8, "An EAN-8 is an EAN/UPC symbology barcode and is derived from the longer International Article Number (EAN-13) code. It was introduced for use on small packages where an EAN-13 barcode would be too large; for example on cigarettes, pencils, and chewing gum packets. It is encoded identically to the 12 digits of the UPC-A barcode, except that it has 4 (rather than 6) digits in each of the left and right halves. EAN - 8 barcodes may be used to encode GTIN - 8(8 - digit Global Trade Identification Numbers) which are product identifiers from the GS1 System.A GTIN - 8 begins with a 2 - or 3 - digit GS1 prefix(which is assigned to each national GS1 authority) followed by a 5 - or 4 - digit item reference element depending on the length of the GS1 prefix), and a checksum digit. EAN - 8 codes are common throughout the world, and companies may also use them to encode RCN-8(8 - digit Restricted Circulation Numbers), and use them to identify own-brand products sold only in their stores. RCN - 8 are a subset of GTIN - 8 which begin with a first digit of 0 or 2.", "https://en.wikipedia.org/wiki/EAN-8", @".\Image\EAN_8.png");
            var EAN_13 = new Format(BarcodeFormat.EAN_13, "The International Article Number (also known as European Article Number or EAN) is a standard describing a barcode symbology and numbering system used in global trade to identify a specific retail product type, in a specific packaging configuration, from a specific manufacturer. The standard has been subsumed in the Global Trade Item Number standard from the GS1 organization; the same numbers can be referred to as GTINs and can be encoded in other barcode symbologies defined by GS1. EAN barcodes are used worldwide for lookup at retail point of sale, but can also be used as numbers for other purposes such as wholesale ordering or accounting. The most commonly used EAN standard is the thirteen - digit EAN - 13, a superset of the original 12 - digit Universal Product Code(UPC - A) standard developed in 1970 by George J.Laurer. An EAN - 13 number includes a 3 - digit GS1 prefix(indicating country of registration or special type of product).A prefix with a first digit of \"0\" indicates a 12 - digit UPC - A code follows.A prefix with first two digits of \"45\" or \"49\" indicates a Japanese Article Number(JAN) follows.", "https://en.wikipedia.org/wiki/International_Article_Number", @".\Image\EAN_13.png");
            var MAXICODE = new Format(BarcodeFormat.MAXICODE, "MaxiCode is a public domain, machine-readable symbol system originally created and used by United Parcel Service. Suitable for tracking and managing the shipment of packages, it resembles a barcode, but uses dots arranged in a hexagonal grid instead of bars. MaxiCode has been standardised under ISO/IEC 16023. A MaxiCode symbol(internally called \"Bird's Eye\", \"Target\", \"dense code\", or \"UPS code\") appears as a 1 inch square, with a bullseye in the middle, surrounded by a pattern of hexagonal dots.It can store about 93 characters of information, and up to 8 MaxiCode symbols can be chained together to convey more data.The centered symmetrical bullseye is useful in automatic symbol location regardless of orientation, and it allows MaxiCode symbols to be scanned even on a package traveling rapidly. MaxiCode symbology was released by UPS in 1992.", "https://en.wikipedia.org/wiki/MaxiCode", @".\Image\MAXICODE.png");
            var QR_CODE = new Format(BarcodeFormat.QR_CODE, "QR code (abbreviated from Quick Response Code) is the trademark for a type of matrix barcode (or two-dimensional barcode) first designed in 1994 for the automotive industry in Japan. A barcode is a machine-readable optical label that contains information about the item to which it is attached. A QR code uses four standardized encoding modes (numeric, alphanumeric, byte/binary, and kanji) to store data efficiently; extensions may also be used. The Quick Response(QR code) system became popular outside the automotive industry due to its fast readability and greater storage capacity compared to standard UPC barcodes.Applications include product tracking, item identification, time tracking, document management, and general marketing. A QR code consists of black squares arranged in a square grid on a white background, which can be read by an imaging device such as a camera, and processed using Reed–Solomon error correction until the image can be appropriately interpreted. The required data is then extracted from patterns that are present in both horizontal and vertical components of the image.", "https://en.wikipedia.org/wiki/QR_code", @".\Image\QR_CODE.png");
            var PDF_417 = new Format(BarcodeFormat.PDF_417, "PDF417 is a stacked linear barcode symbol format used in a variety of applications; primarily transport, identification cards, and inventory management. PDF stands for Portable Data File. The 417 signifies that each pattern in the code consists of bars and spaces, and that each pattern is 17 units long. The PDF417 symbology was invented by Dr. Ynjiun P. Wang at Symbol Technologies in 1991. (Wang 1993) It is ISO standard 15438.", "https://en.wikipedia.org/wiki/PDF417", @".\Image\PDF_417.png");
            var RSS_14 = new Format(BarcodeFormat.RSS_14, "RSS 14 barcode(Reduce Space Symbology) encodes the full 14 - digit EAN.UCC item identification in a symbol that can be omnidirectionally scanned by suitably configured point - of - sale laser scanners.It is the latest barcode types for space - constrained identification from EAN International and the Uniform Code Council, Inc..RSS barcodes have been identified to target the grocery industry and in healthcare, where items are too small to allow for other barcode symbologies.", "https://en.wikipedia.org/wiki/GS1_DataBar", @".\Image\RSS_14.png");
            var RSS_EXPANDED = new Format(BarcodeFormat.RSS_EXPANDED, "RSS Expanded is a variable length linear symbology capable of encoding up to 74 numeric or 41 alphabetic characters", "https://en.wikipedia.org/wiki/GS1_DataBar", @".\Image\RSS_EXPANDED.png");
            var UPC_A = new Format(BarcodeFormat.UPC_A, "The Universal Product Code (UPC) is a barcode symbology that is widely used in the United States, Canada, United Kingdom, Australia, New Zealand, in Europe and other countries for tracking trade items in stores. UPC(technically refers to UPC - A) consists of 12 numeric digits that are uniquely assigned to each trade item.Along with the related EAN barcode, the UPC is the barcode mainly used for scanning of trade items at the point of sale, per GS1 specifications. UPC data structures are a component of GTINs and follow the global GS1 specification, which is based on international standards.But some retailers(clothing, furniture) do not use the GS1 system(rather other barcode symbologies or article number systems). On the other hand, some retailers use the EAN/ UPC barcode symbology, but without using a GTIN (for products sold in their own stores only).", "https://en.wikipedia.org/wiki/Universal_Product_Code", @".\Image\UPC_A.png");
            var All_1D = new Format(BarcodeFormat.All_1D, "All_1D", "", @".\Image\All_1D.png");
            var UPC_EAN_EXTENSION = new Format(BarcodeFormat.UPC_EAN_EXTENSION, "To allow the use of UPC barcodes on smaller packages, where a full 12-digit barcode may not fit, a 'zero-suppressed' version of UPC was developed, called UPC-E, in which the number system digit, all trailing zeros in the manufacturer code, and all leading zeros in the product code, are suppressed (omitted). This symbology differs from UPC-A in that it only uses a 6-digit code, does not use M (middle) guard pattern, and the E (end) guard pattern is formed as space-bar-space-bar-space-bar, i.e. UPC-E barcode follows the pattern SDDDDDDE. The way in which a 6-digit UPC-E relates to a 12-digit UPC-A, is determined by UPC-E numerical pattern and UPC-E parity pattern. It can only correspond to UPC-A number system 0 or 1, the value of which, along with the UPC-A check digit, determines the UPC-E parity pattern of the encoding. With the manufacturer code digits represented by X's, and product code digits by N's, then:", "https://en.wikipedia.org/wiki/Universal_Product_Code#UPC-E", @".\Image\UPC_EAN_EXTENSION.png");
            var MSI = new Format(BarcodeFormat.MSI, "MSI (also known as Modified Plessey) is a barcode symbology developed by the MSI Data Corporation, based on the original Plessey Code symbology. It is a continuous symbology that is not self-checking. MSI is used primarily for inventory control, marking storage containers and shelves in warehouse environments.", "https://en.wikipedia.org/wiki/MSI_Barcode", @".\Image\MSI.png");
            var PLESSEY = new Format(BarcodeFormat.PLESSEY, "Plessey Code is a 1D linear barcode symbology based on pulse width modulation, developed in 1971 by The Plessey Company plc, a British-based company. It is one of the first barcode symbology, and is still used in some rare libraries and for shelf tags in retail stores, in part as a solution to their internal requirement for stock control. The system was first used in the early 1970s by J.Sainsbury to identify all of its products on supermarket shelves for its product restocking system. The chief advantages are the relative ease of printing using the dot-matrix printers popular at the time of the code's introduction, and its somewhat higher density than the more common 2 of 5 and 3 of 9 codes. It has later led several variations as Anker Code by ADS Company, Telxon, and MSI (also known as Plessey modified). It is difficult to have the specifications for them nowadays and thus hard to tell the differences between them (except for MSI), because it was mainly available as a paper document and has since been discontinued.", "https://en.wikipedia.org/wiki/Plessey_Code", @".\Image\PLESSEY.png");
            var IMB = new Format(BarcodeFormat.IMB, "The Intelligent Mail Barcode (IM barcode) is a 65-bar barcode for use on mail in the United States. The term \"Intelligent Mail\" refers to services offered by the United States Postal Service for domestic mail delivery. The IM barcode is intended to provide greater information and functionality than its predecessors POSTNET and PLANET. An Intelligent Mail barcode has also been referred to as a One Code Solution and a 4-State Customer Barcode, abbreviated 4CB, 4-CB or USPS4CB. The complete specification can be found in USPS Document USPS-B-3200. It effectively incorporates the routing ZIP code and tracking information included in previously used postal barcode standards. The barcode is applied by the sender; the Postal Service required use of the Intelligent Mail barcode to qualify for automation prices beginning January 28, 2013. Use of the barcode provides increased overall efficiency, including improved deliverability, and new services. ", "https://en.wikipedia.org/wiki/Intelligent_Mail_barcode", @".\Image\IMB.png");

            allFormat.Add(AZTEC);
            allFormat.Add(CODABAR);
            allFormat.Add(CODE_39);
            allFormat.Add(CODE_93);
            allFormat.Add(CODE_128);
            allFormat.Add(DATA_MATRIX);
            allFormat.Add(EAN_8);
            allFormat.Add(EAN_13);
            allFormat.Add(MAXICODE);
            allFormat.Add(QR_CODE);
            allFormat.Add(PDF_417);
            allFormat.Add(RSS_14);
            allFormat.Add(RSS_EXPANDED);
            allFormat.Add(UPC_A);
            allFormat.Add(All_1D);
            allFormat.Add(UPC_EAN_EXTENSION);
            allFormat.Add(MSI);
            allFormat.Add(PLESSEY);
            allFormat.Add(IMB);

            return allFormat;
        }    
    }
}
